#######################################COURSE PROJECT 1#######################################
######PLOT4
png("plot4.png", width=480, height=480)
par(mfrow=c(2,2))
plot(datapro$Global_active_power, type="l", ylab="Global Active Power", xlab="",axes=F)
axis(side=1, at=c(1,1450,2900), labels=c("Thu","Fri","Sat"))
axis(side=2, at=c(0,2,4,6), labels=c("0","2","4","6"))
box()
plot(datapro$Voltage, type="l", xlab="datetime", ylab="Voltage", axes=F) 
axis(side=1, at=c(1,1450,2900), labels=c("Thu","Fri","Sat"))
axis(side=2, at=c(234,238,242,246), labels=c("234","238","242","246"))
box()
plot(datapro$Sub_metering_1, type="l", ylab="Energy sub metering", xlab="", axes=F, col="black", ylim=c(0,40)) 
par(new=T)
plot(datapro$Sub_metering_2, type="l", ylab="Energy sub metering", xlab="", axes=F, col="red", ylim = c(0,40)) 
par(new=T)
plot(datapro$Sub_metering_3, type="l", ylab="Energy sub metering", xlab="", axes=F, col="blue", ylim = c(0,40))
axis(side=2, at=c(0,10,20,30), labels=c("0","10","20","30"))
axis(side=1, at=c(1,1450,2900), labels=c("Thu","Fri","Sat"))
box()
legend("topright", lty=1, col=c("black","red","blue"), legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"))
plot(datapro$Global_reactive_power, type="l", xlab="datetime",ylab="Global_reactive_power", axes=F)
axis(side=1, at=c(1,1450,2900), labels=c("Thu","Fri","Sat"))
axis(side=2, at=c(0.0,0.1,0.2,0.3,0.4,0.5), labels=c("0.0","0.1","0.2","0.3","0.4","0.5"))
box()
dev.off()
